
nav:
  - Home: index.md
  - About: about.md

  - Init:
    - early-init: build/early-init.md
    - init: build/init.md
  - Src:
    - src: build/src/_src.md
    - "build/src/*.md"

  - Misc:
    - "build/src/misc/*.md"
    - "*/*.md"
    - "*.md"
